# Generated by Django 4.2.2 on 2023-12-13 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
